[package]
name = "opus-sys"
version = "0.3.0"
authors = ["Varphone Wong <varphone@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
bindgen = "0.58"
num_cpus = "1.11"
pkg-config = "0.3"